### ISSUE TITLE
The destroy option should prompt you and ask if really want to destroy it.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jorgemoralespou/oc-cluster-wrapper#3]
The ``destroy`` option should by default prompt you and ask if you really want to destroy the cluster to guard against accidentally running it.

If want to avoid the prompt then can accept a ``--force`` option to make it just do it.

**Comment by jorgemoralespou** [comment]
PR welcome. If not the best scripting guy. But I think you're right.
