### ISSUE TITLE
When creating shared volume is ignore path supplied.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jorgemoralespou/oc-cluster-wrapper#5]
The ``create-shared-volume`` has:

```
  local __path=$3

  local __path=$OPENSHIFT_HOME_DIR/volumes/${__volume}
```

So it is ignoring the supplied path.

**Comment by jorgemoralespou** [comment]
Yes for now. I wanted to experiment if things worked before getting more
complexity in.
