### ISSUE TITLE
Should not use Recycle where path supplied for volume, use Retain instead.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jorgemoralespou/oc-cluster-wrapper#6]
When using ``Recycle`` the ``oc cluster up`` instance will attempt to remove files in the directory it is given when the ``pvc`` is deleted. If a file in the volume is read only, then it will actually fail and give up, but is still attempting to remove stuff and if it can it will. When it does fail, it still allows the volume to be reused even though not empty.

Thus when supplying a path for volumes, be it with ``create-volume`` or ``create-shared-volume``, the ``persistentVolumeReclaimPolicy`` should be set to ``Retain`` to avoid someone deleting all there files because they gave a path to stuff in their home directory or elsewhere.

Need perhaps a way of the manually making that volume reusable again.

**Comment by jorgemoralespou** [comment]
Yes. I thought it was retain. I'll fix this.

**Comment by jorgemoralespou** [comment]
@GrahamDumpleton in the docs I created initially, I was thinking on doing a recycle-volume, but this is food for thought
